### REST Client (VSCode Extension)

### Get all todos
GET http://localhost:8000/api/todos

### Create a new todo
POST http://localhost:8000/api/todos
Content-Type: application/json

{
  "title": "New Todo",
  "completed": false
}

### Create demo data
POST http://localhost:8000/api/demo
Content-Type: application/json

{
  "clear": true
}

### Delete all todos
DELETE http://localhost:8000/api/todos
