# Markdownlint configuration
# See: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# デフォルトの設定
default: true

# カスタム設定
MD001: false  # Header levels should only increment by one level at a time
MD003:        # Header style
  style: "atx"
MD004:        # Unordered list style
  style: "dash"
MD007:        # Unordered list indentation
  indent: 2
MD009:        # Trailing spaces
  br_spaces: 2
MD010: false  # Hard tabs (無効化 - エディターの設定に任せる)
MD012:        # Multiple consecutive blank lines
  maximum: 2
MD013:        # Line length
  line_length: 120
  heading_line_length: 150
  code_blocks: false
  tables: false
MD022:        # Headers should be surrounded by blank lines
  lines_above: 1
  lines_below: 1
MD024:        # Multiple headers with the same content
  allow_different_nesting: true
MD025:        # Multiple top level headers in the same document
  front_matter_title: ""
MD026:        # Trailing punctuation in header
  punctuation: ".,;:!?"
MD029:        # Ordered list item prefix
  style: "ordered"
MD030:        # Spaces after list markers
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1
MD033:        # Allow inline HTML
  allowed_elements: ["br", "img", "details", "summary", "kbd", "sub", "sup"]
MD034: false  # Bare URL used (無効化 - 生のURLも許可)
MD036:        # Emphasis used instead of header
  punctuation: ".,;:!?。，；：！？"
MD040:        # Fenced code blocks should have a language specified
  allowed_languages: []
  language_only: false
MD041: false  # First line in file should be a top level header (無効化)
MD046:        # Code block style
  style: "fenced"
MD048:        # Code fence style
  style: "backtick"
