site_name: Todo App Documentation
site_description: Documentation for the Todo Application
site_author: Todo App Team
site_url: https://lightuse.github.io/todo-app
docs_dir: ../
site_dir: ../../site

repo_name: lightuse/todo-app
repo_url: https://github.com/lightuse/todo-app

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
  - Frontend:
    - Architecture: frontend/architecture.md
    - Components: frontend/components.md
    - Testing: frontend/testing.md
  - Backend:
    - API Reference: backend/api.md
    - Database: backend/database.md
    - Models: backend/models.md
  - Development:
    - Setup: development/setup.md
    - Sphinx Setup Guide: development/sphinx-setup.md
    - Sphinx Quick Reference: development/sphinx-quick-ref.md
    - Contributing: development/contributing.md
    - Deployment: development/deployment.md
    - Documentation Validation: development/documentation-validation.md
  - API Documentation:
    - Overview: api/index.md
  - Accessibility: modal-accessibility.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

plugins:
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          paths: [../../backend]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            show_object_full_path: false
            show_category_heading: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra_css:
  - assets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lightuse/todo-app
  version:
    provider: mike
